name: checkout-release-devkit
description: Check out release-devkit at the pinned commit
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        repository: outernet-foundation/release-devkit
        ref: 489427e24ed74a8a5d10a0898d4639c340049fbf
        path: .release-devkit
        persist-credentials: false
