name: Integrate

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

concurrency:
  group: integrate-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  preflight:
    uses: outernet-foundation/github-actions-toolkit/.github/workflows/preflight.yml@c1f000c9ba372403676bf9cd537634c8bd20fea2

  update-pr-draft-release:
    needs: [preflight]
    permissions:
      contents: write
      packages: read
    uses: outernet-foundation/github-actions-toolkit/.github/workflows/update-pr-draft-release.yml@c1f000c9ba372403676bf9cd537634c8bd20fea2
