name: Merge gate

on:
  pull_request:
    branches: [dev]
    types: [labeled]

concurrency:
  group: merge-gate-${{ github.event.pull_request.number }}

permissions:
  contents: read

jobs:
  merge-gate:
    uses: outernet-foundation/github-actions-toolkit/.github/workflows/merge-gate.yml@c1f000c9ba372403676bf9cd537634c8bd20fea2
    secrets:
      merge-bot-private-key: ${{ secrets.MERGE_BOT_APP_PRIVATE_KEY }}
