name: Release

on:
  push:
    branches: [main, dev]

concurrency:
  group: release-${{ github.ref }}

permissions:
  contents: read

jobs:
  prerelease:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: outernet-foundation/github-actions-toolkit/.github/actions/release@c1f000c9ba372403676bf9cd537634c8bd20fea2
        with:
          channel: dev

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: outernet-foundation/github-actions-toolkit/.github/actions/release@c1f000c9ba372403676bf9cd537634c8bd20fea2
        with:
          channel: stable
